# Generated by Django 4.2.20 on 2025-04-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_movie_id_comment_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance')], max_length=50),
        ),
    ]
